Fix soundcloud-v2 error breaking entire search functionality (#52)
https://github.com/7x11x13/soundcloud.py/issues/17

Seems like initializing the SoundCloud class like so:
```
from soundcloud import SoundCloud
soundcloud = SoundCloud()
```

yields this error:

```
Traceback (most recent call last):
  File "<swift>", line 2, in <module>
  File "/Users/armaan/Library/Developer/CoreSimulator/Devices/37058714-0380-486D-A861-CEDEA121FF98/data/Containers/Bundle/Application/EB512344-BF03-4FB1-A70D-99243BB181B5/Arbor.app/app_packages/pytest_download/search.py", line 68, in search_soundcloud
    soundcloud = SoundCloud()
  File "/Users/armaan/Library/Developer/CoreSimulator/Devices/37058714-0380-486D-A861-CEDEA121FF98/data/Containers/Bundle/Application/EB512344-BF03-4FB1-A70D-99243BB181B5/Arbor.app/python_modules/soundcloud/soundcloud.py", line 100, in __init__
    client_id = self.generate_client_id()
  File "/Users/armaan/Library/Developer/CoreSimulator/Devices/37058714-0380-486D-A861-CEDEA121FF98/data/Containers/Bundle/Application/EB512344-BF03-4FB1-A70D-99243BB181B5/Arbor.app/python_modules/soundcloud/soundcloud.py", line 148, in generate_client_id
    raise ClientIDGenerationError(f"Could not find client_id in script '{url}'")
soundcloud.exceptions.ClientIDGenerationError: Could not find client_id in script 'https://a-v2.sndcdn.com/assets/0-52ee434e.js'
pythonExecAndGetString error: Failed to execute code
```

The issue is this broke both YouTube search and SoundCloud search since
the SoundCloud() initialization is called at the top-level of search.py,
resulting in a generic "No results found" UI result.

Therefore, the solution is to call the initializations in their
respective functions so one part doesn't break the other.

SoundCloud search still doesn't work though.